### ISSUE TITLE
Evaluate - Adding copy functionality to flatmap

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/flatmap#3]
This is probably too much magic... but worth reviewing.

I was wondering if it would make sense to support `copy` as a new type of operation. 

One of the use cases I am thinking of is when you want to extract nested parameters for a sequential proxy temporarily but you still need the response as is. The `move` is going to remove the element from its position, so it doesn't cover the case.

Sequential proxy could also support nested parameters, but not sure if I would do it.

Thoughts?

**Comment by ihippik** [comment]
My opinion is a hack, so it's better to throw our efforts to support nested parameters for sequential requests.

**Comment by ihippik** [comment]
But in this plugin, I would add the functionality to filter the array by one of the values of its element.
You are right that this is probably a job for krakend, but sometimes we really do not control the backend and it would be great to have such an opportunity) If I have time, I will try to help you with PR.

**Comment by kpacha** [comment]
regarding the `copy` feature, I have a question: should the copy operation add a new pointer to the value from the destination or should it do a deep copy of the value (and its possible children)?

**Comment by alombarte** [comment]
I would close this issue for now, especially now that we can access nested parameters. If anyone else has an interest in this, we can reopen.
